[tools]
"cargo:tlrc" = "latest"
"cargo:sd" = "latest"
bat = "latest"
cmake = "latest"
delta = "latest"
difftastic = "latest"
dust = "latest"
fd = "latest"
fx = "latest"
fzf = "latest"
glow = "latest"
hyperfine = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
node = "lts"
rg = "latest"
usage = "latest"
yazi = "latest"
zoxide = "latest"

[settings]
experimental = true
