repos:
-   repo: local
    hooks:
    - id: check-added-files
      name: Check for Lua A|M|D files in nvim folder
      entry: .git/hooks/check-added-files-nvim.sh
      language: system
      types: [lua]
      verbose: false
      always_run: true
      pass_filenames: false
